#!/usr/bin/perl -w
# script will use scv reports generated by ne_rep.pl to create
# html tables
use Time::localtime;
$in_file = "Interface_status_report.csv";
@file_list = `ls -1 /data/engineering/networking/status/output/*out`;
$after_file = $file_list[2];
chomp $after_file;
$bef_file = "$after_file\.before";
$before = `ls -l $bef_file`;
$after  =  `ls -l $after_file`;
# print $after,$before,"\n";
     
(@file_list) = split(" ",$after);
$after_file = "$file_list[5] $file_list[6] $file_list[7]";
(@file_list) = split(" ",$before);
$bef_file = "$file_list[5] $file_list[6] $file_list[7]";

open(FILE, $in_file) || die "cant open $in_file file \n";
@compr = <FILE>;
close(FILE);
$in_file = "Interface_exception_report.csv";
open(FILE, $in_file) || die "cant open $in_file file \n";
@except = <FILE>;
close(FILE);
$out_file = "Interface_status.html";
open(FILE, ">$out_file") || die "cant open except_out.csv file \n";
$out_file = "Interface_exceptions.html";
$date = localtime->year() + 1900;
$date .= "/";
$date .= (localtime->mon()+1);
$date .= "/";
$date .= localtime->mday();
print FILE "<html><body>\n";
print FILE "<p>\n";
print FILE "<img src=\"top_short3.gif\"\n";
print FILE "width=\"259\" height=\"57\" border=\"0\" alt=\"\">\n";
print FILE "</p>\n";
print FILE "<h1>Interface Status Report</h1>\n";
print FILE "<h1>As of $date </h1>\n"; 
print FILE "<table border=\"1\"\n>";
print FILE "<tr>\n";
print FILE "  <th>Router</th>\n";
print FILE "  <th>Interface</th>\n";
print FILE "  <th>Description</th>\n";
print FILE "  <th>Status</th>\n";
print FILE "</tr>\n";

foreach $line (@compr)
  {
   chomp $line;
   print FILE "<tr>\n";
   (@elements) = split(",",$line);
   foreach $element (@elements)
     {
     if($element eq"" ) {$element = ".";}
     print FILE "<td>$element</td>\n";
     }
   print FILE "</tr>\n";
  }
print FILE "</table\n>";
print FILE "</body></html>\n";

close(FILE);
$out_file = "Interface_exceptions.html";
open(FILE, ">$out_file") || die "cant open $out_file file \n";
print FILE "<html><body>\n";
print FILE "<p>\n";
print FILE "<img src=\"top_short3.gif\"\n";
print FILE "width=\"259\" height=\"57\" border=\"0\" alt=\"\">\n";
print FILE "</p>\n";
print FILE "<h1>Interface Status Change Report</h1>\n";
print FILE "<h2>Comparing $bef_file and $after_file </h2>\n";
#print FILE "<h1>$date</h1>\n";
print FILE "<table border=\"1\"\n>";
print FILE "<tr>\n";
print FILE "  <th>Router</th>\n";
print FILE "  <th>Interface</th>\n";
print FILE "  <th>Description</th>\n";
print FILE "  <th>Status</th>\n";
print FILE "  <th>New Description</th>\n";
print FILE "  <th>New Status</th>\n";
print FILE "  <th>Comments</th>\n";
print FILE "</tr>\n";

foreach $line (@except)
  {
   chomp $line;
   print FILE "<tr>\n";
   (@elements) = split(",",$line);
     if($#elements <3) {$elements[3] = ".";}
   foreach $element (@elements)
     {
     if(length($element) <=0 ) {$element = ".";}
     print FILE "<td>$element</td>\n";
     }
   print FILE "</tr>\n";
  }
print FILE "</table\n>";
print FILE "</body></html>\n";

close(FILE);

